spring.datasource.url=jdbc:mariadb://localhost:3306/projeto_passe
spring.datasource.username=${DB_USERNAME:daniel_api}
spring.datasource.password=${DB_PASSWORD:Passe123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
